/**
 * Debug Package Packager
 *
 * Creates a zip file containing all debug package contents.
 */

import archiver from 'archiver';
import * as fs from 'fs';
import * as path from 'path';

export interface PackageContents {
	'system-info.json': unknown;
	'settings.json': unknown;
	'agents.json': unknown;
	'external-tools.json': unknown;
	'windows-diagnostics.json': unknown;
	'sessions.json': unknown;
	'groups.json': unknown;
	'processes.json': unknown;
	'logs.json': unknown;
	'errors.json': unknown;
	'web-server.json': unknown;
	'storage-info.json': unknown;
	'group-chats.json': unknown;
	'batch-state.json': unknown;
	'collection-errors.json'?: unknown;
}

/**
 * Generate the README content for the debug package.
 */
function generateReadme(): string {
	return `# Maestro Debug Package

This package was generated by Maestro for debugging purposes.

## Contents

- system-info.json - OS and hardware information
- settings.json - Application settings (sensitive data redacted)
- agents.json - AI agent configurations and availability
- external-tools.json - External dependencies (shells, git, gh CLI, cloudflared)
- sessions.json - Session metadata (no conversation content)
- groups.json - Group structure (no group names)
- processes.json - Active process information
- logs.json - Recent system logs
- errors.json - Error states and recent errors
- web-server.json - Web server and tunnel status
- storage-info.json - Storage locations and sizes
- group-chats.json - Group chat metadata
- batch-state.json - Auto Run state

## Submission

To submit this debug package:
1. Open a GitHub issue at https://github.com/RunMaestro/Maestro/issues
2. Describe the problem you encountered
3. Attach this zip file to the issue

## Privacy

Support packages are usually attached to public GitHub issues, so this one
carries no information that identifies you or your work.

This package does NOT contain:
- Your conversations with AI agents
- API keys, tokens, passwords, or secrets
- File contents from your projects
- Your username, your computer's name, or SSH remote identities
- File paths, folder names, project names, or repository names
- Agent binary paths or installation locations
- Session, group, or group chat names
- Directory file listings

## Reading redacted paths

Every path is replaced with a descriptor like:

    [path#3f9a1c04 root=home depth=4 ext=.json spaces]

- path#<id> - a per-package fingerprint. Identical ids mean identical paths, so
  you can still tell whether two agents share a working directory. The id is
  salted per package and cannot be reversed or matched against another package.
- root - where the path starts: home, /, a drive letter, unc, or rel
- depth - number of path segments below the root
- ext - file extension, when the path names a file
- spaces / non-ascii - present when the path contains those characters, the
  usual cause of process spawn failures

URLs are reduced to their scheme and registrable domain
([url#... https://example.com/[redacted]]). Log messages are swept for paths,
URLs, usernames, and hostnames, and truncated.
`;
}

/**
 * Create a zip package containing all debug data.
 */
export async function createZipPackage(
	outputDir: string,
	contents: Partial<PackageContents>
): Promise<{ path: string; sizeBytes: number }> {
	// Generate timestamp for filename
	const now = new Date();
	const timestamp = now.toISOString().replace(/[:.]/g, '-').slice(0, 19);
	const filename = `maestro-debug-${timestamp}.zip`;
	const outputPath = path.join(outputDir, filename);

	// Ensure output directory exists
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true });
	}

	return new Promise((resolve, reject) => {
		const output = fs.createWriteStream(outputPath);
		const archive = archiver('zip', {
			zlib: { level: 9 }, // Maximum compression
		});

		output.on('close', () => {
			resolve({
				path: outputPath,
				sizeBytes: archive.pointer(),
			});
		});

		archive.on('error', (err) => {
			reject(err);
		});

		// Pipe archive data to the file
		archive.pipe(output);

		// Add each JSON file to the archive
		for (const [filename, data] of Object.entries(contents)) {
			if (data !== undefined) {
				const jsonContent = JSON.stringify(data, null, 2);
				archive.append(jsonContent, { name: filename });
			}
		}

		// Add README
		archive.append(generateReadme(), { name: 'README.md' });

		// Finalize the archive
		archive.finalize();
	});
}
