// Completions command - emit a shell completion script for bash, zsh, or fish.
//
// The script is generated by introspecting the live Commander program tree, so
// it stays in sync with the registered commands automatically: new commands and
// flags appear in completions the next time the user regenerates the script.
//
// Usage:
//   openwizardai-cli completions zsh  >> ~/.zshrc            (or a fpath file)
//   openwizardai-cli completions bash >> ~/.bashrc
//   openwizardai-cli completions fish >  ~/.config/fish/completions/openwizardai-cli.fish

import type { Command } from 'commander';
import { formatError } from '../output/formatter';
import { ExitCode } from '../exit-codes';

interface CommandNode {
	name: string;
	flags: string[];
	subcommands: CommandNode[];
}

/** Collect the long-form flags declared directly on a command. */
function collectFlags(cmd: Command): string[] {
	const flags: string[] = [];
	for (const opt of cmd.options) {
		// `opt.long` is the `--foo` form; fall back to the short form if that's all
		// the option has. Skip Commander's auto help (added per-command).
		if (opt.long) flags.push(opt.long);
		else if (opt.short) flags.push(opt.short);
	}
	return flags;
}

/** Recursively build a tree of commands, their subcommands, and their flags. */
function buildTree(cmd: Command): CommandNode {
	return {
		name: cmd.name(),
		flags: collectFlags(cmd),
		subcommands: cmd.commands.map((c) => buildTree(c as Command)),
	};
}

function bashScript(root: CommandNode): string {
	// Flatten into "path -> completions" associative entries. The path is the
	// space-joined command chain after the program name.
	const lines: string[] = [];
	const topNames = root.subcommands.map((c) => c.name).join(' ');
	const globalFlags = root.flags.join(' ');

	// Build a case over the first subcommand word.
	const subCases: string[] = [];
	for (const sub of root.subcommands) {
		const subSubNames = sub.subcommands.map((s) => s.name).join(' ');
		const completions = [subSubNames, sub.flags.join(' ')].filter(Boolean).join(' ');
		subCases.push(`    ${sub.name}) words="${completions}" ;;`);
	}

	lines.push(`# bash completion for openwizardai-cli`);
	lines.push(`_openwizardai_cli() {`);
	lines.push(`  local cur prev words cword`);
	lines.push(`  COMPREPLY=()`);
	lines.push(`  cur="\${COMP_WORDS[COMP_CWORD]}"`);
	lines.push(`  if [ "$COMP_CWORD" -eq 1 ]; then`);
	lines.push(`    COMPREPLY=( $(compgen -W "${topNames} ${globalFlags}" -- "$cur") )`);
	lines.push(`    return`);
	lines.push(`  fi`);
	lines.push(`  local words=""`);
	lines.push(`  case "\${COMP_WORDS[1]}" in`);
	lines.push(...subCases);
	lines.push(`    *) words="${globalFlags}" ;;`);
	lines.push(`  esac`);
	lines.push(`  COMPREPLY=( $(compgen -W "$words" -- "$cur") )`);
	lines.push(`}`);
	lines.push(`complete -F _openwizardai_cli openwizardai-cli`);
	return lines.join('\n');
}

function zshScript(root: CommandNode): string {
	const lines: string[] = [];
	const topPairs = root.subcommands
		.map((c) => `'${c.name}:${(c.subcommands.length ? 'group' : 'command').replace(/'/g, '')}'`)
		.join(' ');

	const subCases: string[] = [];
	for (const sub of root.subcommands) {
		const items = [...sub.subcommands.map((s) => s.name), ...sub.flags].join(' ');
		subCases.push(`      ${sub.name}) compadd ${items} ;;`);
	}

	lines.push(`#compdef openwizardai-cli`);
	lines.push(`_openwizardai_cli() {`);
	lines.push(`  local -a top`);
	lines.push(`  top=(${topPairs})`);
	lines.push(`  if (( CURRENT == 2 )); then`);
	lines.push(`    _describe 'command' top`);
	lines.push(`    compadd ${root.flags.join(' ')}`);
	lines.push(`    return`);
	lines.push(`  fi`);
	lines.push(`  case "\${words[2]}" in`);
	lines.push(...subCases);
	lines.push(`      *) compadd ${root.flags.join(' ')} ;;`);
	lines.push(`  esac`);
	lines.push(`}`);
	lines.push(`_openwizardai_cli "$@"`);
	return lines.join('\n');
}

function fishScript(root: CommandNode): string {
	const lines: string[] = [];
	lines.push(`# fish completion for openwizardai-cli`);
	// Top-level commands: only when no subcommand seen yet.
	lines.push(`function __openwizardai_cli_no_subcommand`);
	lines.push(`  set -l cmd (commandline -opc)`);
	lines.push(`  test (count $cmd) -eq 1`);
	lines.push(`end`);
	for (const sub of root.subcommands) {
		const desc = sub.subcommands.length ? 'command group' : 'command';
		lines.push(
			`complete -c openwizardai-cli -n __openwizardai_cli_no_subcommand -a ${sub.name} -d '${desc}'`
		);
	}
	// Per-subcommand: complete that command's subcommands and flags.
	for (const sub of root.subcommands) {
		for (const ss of sub.subcommands) {
			lines.push(
				`complete -c openwizardai-cli -n "__fish_seen_subcommand_from ${sub.name}" -a ${ss.name} -d 'subcommand'`
			);
		}
		for (const flag of sub.flags) {
			const long = flag.replace(/^--/, '');
			lines.push(
				`complete -c openwizardai-cli -n "__fish_seen_subcommand_from ${sub.name}" -l ${long}`
			);
		}
	}
	return lines.join('\n');
}

export function completions(program: Command, shell: string): void {
	const tree = buildTree(program);
	const normalized = shell.trim().toLowerCase();
	switch (normalized) {
		case 'bash':
			console.log(bashScript(tree));
			break;
		case 'zsh':
			console.log(zshScript(tree));
			break;
		case 'fish':
			console.log(fishScript(tree));
			break;
		default:
			console.error(formatError(`Unsupported shell "${shell}". Use one of: bash, zsh, fish.`));
			process.exit(ExitCode.InvalidUsage);
	}
}
